name: test

on:
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: build theme
    strategy:
      fail-fast: false
      matrix:
        python-version:
          ["3.8", "3.9", "3.10", "3.11", "pypy-3.8", "pypy-3.9", "pypy-3.10"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .
      - name: Build Themes
        run: |
          mkdocs build -v --strict
